using System.Text;
using System.Text.RegularExpressions;
using Cnblogs.Architecture.Tool.Manifest;

namespace Cnblogs.Architecture.Tool.Generation;

/// <summary>
///     Turns an <see cref="EndpointManifest" /> into generated C# source files: one <c>IXxxService</c> /
///     <c>XxxService</c> pair per group, plus a <c>ServiceAgentExtensions</c> DI-registration file. Collapses
///     nullable-route expansions into single methods and maps each endpoint shape to the matching
///     <c>CqrsServiceAgent&lt;TError&gt;</c> helper.
/// </summary>
internal sealed class ServiceAgentEmitter
{
    private const string AutoGeneratedBanner =
        "// <auto-generated>\n"
        + "//     This code was generated by dotnet-cnb (dotnet cnb serviceagent generate).\n"
        + "//     Do not edit manually; regenerate by running the tool against the API project.\n"
        + "// </auto-generated>\n"
        + "#nullable enable\n";

    private static readonly Regex RouteTokenRegex = new(
        @"\{(\*?)([A-Za-z_][A-Za-z0-9_]*)([^}]*)\}",
        RegexOptions.Compiled);

    private readonly List<string> _diagnostics = [];

    // Payload-POCO tables, rebuilt per Emit() call. Keyed by body-type identity (not by endpoint) so a command mapped at
    // multiple routes shares a single POCO — otherwise the duplicate class declaration would not compile in one namespace.
    private readonly Dictionary<string, string> _pocoNameByBodyType = new(StringComparer.Ordinal);
    private readonly Dictionary<string, PocoDefinition> _pocoDefinitions = new(StringComparer.Ordinal);

    /// <summary>Warnings collected during emission (e.g. skipped endpoint shapes).</summary>
    public IReadOnlyList<string> Diagnostics => _diagnostics;

    /// <summary>
    ///     The API version substituted for <c>{version:apiVersion}</c> route tokens (the API-versioning route-group
    ///     convention). Defaults to <c>"1"</c>.
    /// </summary>
    public string ApiVersion { get; init; } = "1";

    /// <summary>Emit all source files for the manifest, using <paramref name="namespace" /> for the generated types.</summary>
    public List<EmittedFile> Emit(EndpointManifest manifest, string @namespace)
    {
        _diagnostics.Clear();
        _pocoNameByBodyType.Clear();
        _pocoDefinitions.Clear();
        BuildPocoTables(manifest);
        var files = new List<EmittedFile>();
        foreach (var group in manifest.Groups)
        {
            var renderer = new ClrTypeRenderer();
            var plans = BuildPlans(group, renderer);
            var usings = BuildUsings(renderer.ImportedNamespaces);
            files.Add(
                new EmittedFile
                {
                    FileName = "I" + group.Name + "Service.cs",
                    Content = RenderInterface(group, @namespace, plans, usings)
                });
            files.Add(
                new EmittedFile
                {
                    FileName = group.Name + "Service.cs", Content = RenderClass(group, @namespace, plans, usings)
                });
        }

        files.Add(
            new EmittedFile
            {
                FileName = "ServiceAgentExtensions.cs",
                IsExtensionsFile = true,
                Content = RenderExtensions(manifest, @namespace)
            });
        files.AddRange(RenderPayloadContracts(@namespace));
        return files;
    }

    /// <summary>
    ///     Assign a generated POCO name to each distinct command body type that carries a payload contract, reserving
    ///     the names the generator already emits (service classes, the extensions class) so a derived payload name
    ///     cannot collide. One command mapped at several routes shares a single POCO.
    /// </summary>
    private void BuildPocoTables(EndpointManifest manifest)
    {
        var reserved = new HashSet<string>(StringComparer.Ordinal) { "ServiceAgentExtensions" };
        foreach (var group in manifest.Groups)
        {
            reserved.Add(group.Name + "Service");
            reserved.Add("I" + group.Name + "Service");
        }

        foreach (var endpoint in manifest.Groups.SelectMany(g => g.Endpoints))
        {
            if (endpoint.PayloadContract is null)
            {
                continue;
            }

            var bodyParam = endpoint.Parameters.FirstOrDefault(p => p.Source == ParameterSource.Body);
            if (bodyParam is null)
            {
                continue;
            }

            var key = BodyKey(bodyParam.ClrType);
            if (_pocoDefinitions.ContainsKey(key))
            {
                continue;
            }

            var name = UniqueName(DerivePocoName(endpoint.RequestTypeName), reserved);
            _pocoNameByBodyType[key] = name;
            _pocoDefinitions[key] = new PocoDefinition(name, endpoint.PayloadContract.Properties);
        }
    }

    private List<MethodPlan> BuildPlans(ManifestGroup group, ClrTypeRenderer renderer)
    {
        // Render the error type so its namespace is collected into the file's using set.
        if (group.ErrorType is not null)
        {
            renderer.Render(group.ErrorType);
        }

        var clusters = ClusterEndpoints(group.Endpoints);
        var plans = new List<MethodPlan>();
        foreach (var cluster in clusters)
        {
            plans.AddRange(BuildPlansForCluster(cluster, renderer));
        }

        // C# requires required parameters before optional ones; stable-partition so this holds regardless of how
        // route/query/body params were ordered (e.g. nullable route params carry '= null' defaults).
        foreach (var plan in plans)
        {
            plan.Parameters = OrderByOptionality(plan.Parameters);
        }

        SkipDuplicateSignatures(plans);
        return plans;
    }

    private static List<MethodParam> OrderByOptionality(List<MethodParam> parameters)
    {
        return parameters.Where(p => p.Default is null)
            .Concat(parameters.Where(p => p.Default is not null))
            .ToList();
    }

    private void SkipDuplicateSignatures(List<MethodPlan> plans)
    {
        // Two endpoints (e.g. the same command mapped at different routes) can yield methods with identical name
        // and parameter types. C# forbids duplicate declarations, so keep the first and skip the rest.
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var plan in plans)
        {
            if (plan.IsSkipped)
            {
                continue;
            }

            var signature = plan.Name + "(" + string.Join(",", plan.Parameters.Select(p => p.Type)) + ")";
            if (!seen.Add(signature))
            {
                plan.IsSkipped = true;
                plan.SkipReason = "duplicate method signature (same name and parameter types as another endpoint); "
                                  + "split the route groups with WithServiceAgentGroup or use a distinct route";
                _diagnostics.Add($"Skipped duplicate '{plan.Name}' (same signature as another endpoint).");
            }
        }
    }

    /// <summary>
    ///     Group endpoints that resolve to the same generated method: nullable-route expansions of one
    ///     <c>MapQuery</c> call share a request type and a normalized route shape and collapse into one method.
    /// </summary>
    private List<List<ManifestEndpoint>> ClusterEndpoints(List<ManifestEndpoint> endpoints)
    {
        return endpoints
            .GroupBy(e => (e.RequestTypeName, NormalizeRoute(e.Route), e.HttpMethod, NonRouteSignature(e)))
            .Select(g => g.ToList())
            .ToList();
    }

    private static string NonRouteSignature(ManifestEndpoint endpoint)
    {
        var nonRoute = endpoint.Parameters.Where(p => p.Source != ParameterSource.Route).Select(p => p.Name + p.Source);
        return string.Join("|", nonRoute);
    }

    private static string NormalizeRoute(string route)
    {
        var tokenized = RouteTokenRegex.Replace(route, "{}");
        var segments = tokenized.Split('/');
        for (var i = 0; i < segments.Length; i++)
        {
            if (segments[i] == "-")
            {
                segments[i] = "{}";
            }
        }

        return string.Join('/', segments);
    }

    private List<MethodPlan> BuildPlansForCluster(List<ManifestEndpoint> cluster, ClrTypeRenderer renderer)
    {
        var canonical = cluster.OrderByDescending(e => e.Route.Count(c => c == '{')).First();
        var name = DeriveMethodName(canonical.RequestTypeName);
        var nullableRouteParams = canonical.NullableRouteParameters.ToHashSet(StringComparer.OrdinalIgnoreCase);

        var plans = new List<MethodPlan>();

        // Primary method (GET item/list/paged, or a command).
        var primary = BuildPrimaryPlan(canonical, name, nullableRouteParams, renderer);
        plans.Add(primary);

        // HEAD companion for single-item queries that enabled it. Guard on the skip flag (BuildPrimaryPlan returns
        // a Skipped plan, never null) and on the Item shape (HEAD/404 semantics only hold for single-item lookups;
        // list/paged queries never return 404).
        if (canonical is { IsQuery: true, EnableHead: true, ResponseShape: ResponseShape.Item }
            && primary is { IsSkipped: false })
        {
            plans.Add(BuildHeadPlan(canonical, name, nullableRouteParams, renderer));
        }

        return plans;
    }

    private MethodPlan BuildPrimaryPlan(
        ManifestEndpoint endpoint,
        string name,
        HashSet<string> nullableRouteParams,
        ClrTypeRenderer renderer)
    {
        var paramNames = new HashSet<string>(StringComparer.Ordinal);

        var (urlExpr, routeParams, urlDiagnostic) = BuildUrlExpression(endpoint, nullableRouteParams);
        if (urlDiagnostic is not null)
        {
            _diagnostics.Add($"Skipped '{name}' ({endpoint.HttpMethod} {endpoint.Route}): {urlDiagnostic}.");
            return MethodPlan.Skipped(name, urlDiagnostic);
        }

        var queryParams = endpoint.Parameters.Where(p => p.Source == ParameterSource.Query).ToList();
        var bodyParam = endpoint.Parameters.FirstOrDefault(p => p.Source == ParameterSource.Body);

        List<MethodParam> signature;
        string returnType;
        string call;

        if (endpoint.IsQuery)
        {
            var paged = endpoint.ResponseShape == ResponseShape.PagedList;
            var filterQueryParams = paged
                ? queryParams.Where(p => !IsPagingProperty(p.Name)).ToList()
                : queryParams;

            signature = BuildQuerySignature(routeParams, filterQueryParams, paged, renderer, paramNames);
            var fullUrl = AppendQuery(urlExpr, signature);

            if (endpoint.ResponseShape == ResponseShape.Item)
            {
                // The renderer already appends '?' for Nullable<T>; strip it so we add exactly one (Task<T?>).
                var view = StripTrailingNullable(renderer.Render(endpoint.ResponseType));
                returnType = "Task<" + view + "?>";
                call = "GetItemAsync<" + view + ">(" + fullUrl + ")";
            }
            else if (endpoint.ResponseShape == ResponseShape.List)
            {
                var element = renderer.Render(GetElement(endpoint.ResponseType));
                returnType = "Task<List<" + element + ">>";
                call = "ListItemsAsync<List<" + element + ">>(" + fullUrl + ")";
            }
            else if (endpoint.ResponseShape == ResponseShape.PagedList)
            {
                var element = renderer.Render(GetElement(endpoint.ResponseType));
                returnType = "Task<PagedList<" + element + ">>";
                call = "ListPagedItemsAsync<" + element + ">(" + fullUrl + ", pageIndex, pageSize, orderByString)";
            }
            else
            {
                _diagnostics.Add(
                    $"Skipped '{name}' ({endpoint.HttpMethod} {endpoint.Route}): unsupported query response shape {endpoint.ResponseShape}.");
                return MethodPlan.Skipped(name, "unsupported query response shape");
            }
        }
        else
        {
            var bodyTypeOverride = ResolveBodyTypeOverride(endpoint, bodyParam);
            signature = BuildCommandSignature(routeParams, queryParams, bodyParam, bodyTypeOverride, renderer, paramNames);
            var fullUrl = AppendQuery(urlExpr, signature);
            var (cmdReturn, cmdCall, cmdReason) = BuildCommandCall(endpoint, fullUrl, bodyParam, bodyTypeOverride, renderer);
            if (cmdReason is not null)
            {
                _diagnostics.Add($"Skipped '{name}' ({endpoint.HttpMethod} {endpoint.Route}): {cmdReason}.");
                return MethodPlan.Skipped(name, cmdReason);
            }

            returnType = cmdReturn;
            call = cmdCall;
        }

        return new MethodPlan
        {
            Name = name,
            ReturnType = returnType,
            Parameters = signature,
            BodyExpression = call,
            IsSkipped = false
        };
    }

    private MethodPlan BuildHeadPlan(
        ManifestEndpoint endpoint,
        string name,
        HashSet<string> nullableRouteParams,
        ClrTypeRenderer renderer)
    {
        var paramNames = new HashSet<string>(StringComparer.Ordinal);
        var (urlExpr, routeParams, _) = BuildUrlExpression(endpoint, nullableRouteParams);
        var queryParams = endpoint.Parameters.Where(p => p.Source == ParameterSource.Query && !IsPagingProperty(p.Name))
            .ToList();
        var signature = BuildQuerySignature(routeParams, queryParams, false, renderer, paramNames);
        var fullUrl = AppendQuery(urlExpr, signature);
        var baseName = name.EndsWith("Async", StringComparison.Ordinal)
            ? name.Substring(0, name.Length - "Async".Length)
            : name;
        if (baseName.StartsWith("Get", StringComparison.Ordinal))
        {
            baseName = baseName.Substring("Get".Length);
        }

        var headName = "Has" + baseName + "Async";

        return new MethodPlan
        {
            Name = headName,
            ReturnType = "Task<bool>",
            Parameters = signature,
            BodyExpression = "HasItemAsync(" + fullUrl + ")",
            IsSkipped = false
        };
    }

    private static bool IsPagingProperty(string name)
    {
        return string.Equals(name, "PagingParams", StringComparison.OrdinalIgnoreCase)
               || string.Equals(name, "OrderByString", StringComparison.OrdinalIgnoreCase);
    }

    private List<MethodParam> BuildCommandSignature(
        List<RouteParam> routeParams,
        List<ManifestParameter> queryParams,
        ManifestParameter? bodyParam,
        string? bodyTypeOverride,
        ClrTypeRenderer renderer,
        HashSet<string> usedNames)
    {
        var signature = new List<MethodParam>();
        // The body argument is always named 'payload' (the base helper call uses that literal); reserve it first so
        // a query/route parameter whose camelCase name is 'payload' is uniqued (e.g. payload1) instead of colliding.
        if (bodyParam is not null)
        {
            usedNames.Add("payload");
        }

        AddRouteParams(signature, routeParams, renderer, usedNames);
        foreach (var query in queryParams)
        {
            signature.Add(BuildParam(query, renderer, usedNames, forceCamel: true));
        }

        if (bodyParam is not null)
        {
            signature.Add(BuildBodyParam(bodyParam, renderer, bodyTypeOverride));
        }

        return signature;
    }

    private List<MethodParam> BuildQuerySignature(
        List<RouteParam> routeParams,
        List<ManifestParameter> queryParams,
        bool paged,
        ClrTypeRenderer renderer,
        HashSet<string> usedNames)
    {
        var signature = new List<MethodParam>();
        AddRouteParams(signature, routeParams, renderer, usedNames);
        foreach (var query in queryParams)
        {
            signature.Add(BuildParam(query, renderer, usedNames, forceCamel: true));
        }

        if (paged)
        {
            signature.Add(new MethodParam("pageIndex", "int?", " = null"));
            signature.Add(new MethodParam("pageSize", "int?", " = null"));
            signature.Add(new MethodParam("orderByString", "string?", " = null"));
        }

        return signature;
    }

    private void AddRouteParams(
        List<MethodParam> signature,
        List<RouteParam> routeParams,
        ClrTypeRenderer renderer,
        HashSet<string> usedNames)
    {
        foreach (var route in routeParams)
        {
            var type = renderer.Render(route.Parameter.ClrType);
            if (route is { IsNullable: true, Parameter.ClrType.IsNullable: false })
            {
                type += "?";
            }

            var paramName = UniqueName(ToCamelCase(route.Parameter.Name), usedNames);
            signature.Add(new MethodParam(paramName, type, route.IsNullable ? " = null" : null));
        }
    }

    private MethodParam BuildParam(
        ManifestParameter parameter,
        ClrTypeRenderer renderer,
        HashSet<string> usedNames,
        bool forceCamel)
    {
        var type = renderer.Render(parameter.ClrType);
        if (parameter is { IsNullable: true, ClrType.IsNullable: false })
        {
            type += "?";
        }

        var name = UniqueName(forceCamel ? ToCamelCase(parameter.Name) : parameter.Name, usedNames);
        var @default = parameter is { HasDefaultValue: true, DefaultValueLiteral: not null }
            ? " = " + parameter.DefaultValueLiteral
            : (parameter.IsNullable ? " = null" : null);
        return new MethodParam(name, type, @default, ToCamelCase(parameter.Name));
    }

    private static MethodParam BuildBodyParam(
        ManifestParameter parameter,
        ClrTypeRenderer renderer,
        string? bodyTypeOverride)
    {
        // When a payload POCO is generated for this body, use its name directly and never render the command type —
        // that keeps the command's namespace out of the file's using set.
        var type = bodyTypeOverride ?? renderer.Render(parameter.ClrType);
        if (parameter is { IsNullable: true, ClrType.IsNullable: false })
        {
            type += "?";
        }

        return new MethodParam("payload", type, null);
    }

    /// <summary>
    ///     Build the return type (with an <c>(error)</c> placeholder for the group's error type, replaced later) and
    ///     the base-class call expression for a command. Returns a skip reason when no base helper matches the shape.
    /// </summary>
    private (string ReturnType, string Call, string? Reason) BuildCommandCall(
        ManifestEndpoint endpoint,
        string url,
        ManifestParameter? bodyParam,
        string? bodyTypeOverride,
        ClrTypeRenderer renderer)
    {
        var verb = endpoint.HttpMethod.ToUpperInvariant();
        var hasResult = endpoint is { ResponseShape: ResponseShape.Item, ResponseType: not null };
        var view = hasResult ? renderer.Render(endpoint.ResponseType) : null;
        var payloadType = bodyParam is null ? null : (bodyTypeOverride ?? renderer.Render(bodyParam.ClrType));

        switch (verb)
        {
            case "POST":
                if (hasResult && bodyParam is not null)
                {
                    return ("Task<CommandResponse<" + view + ", (error)>>",
                        "PostCommandAsync<" + view + ", " + payloadType + ">(" + url + ", payload)", null);
                }

                if (!hasResult && bodyParam is not null)
                {
                    return ("Task<CommandResponse<(error)>>",
                        "PostCommandAsync<" + payloadType + ">(" + url + ", payload)", null);
                }

                if (!hasResult && bodyParam is null)
                {
                    return ("Task<CommandResponse<(error)>>", "PostCommandAsync(" + url + ")", null);
                }

                return (string.Empty, string.Empty, "POST command with a result requires a body payload");
            case "PUT":
                if (hasResult && bodyParam is not null)
                {
                    return ("Task<CommandResponse<" + view + ", (error)>>",
                        "PutCommandAsync<" + view + ", " + payloadType + ">(" + url + ", payload)", null);
                }

                if (!hasResult && bodyParam is not null)
                {
                    return ("Task<CommandResponse<(error)>>",
                        "PutCommandAsync<" + payloadType + ">(" + url + ", payload)", null);
                }

                if (!hasResult && bodyParam is null)
                {
                    return ("Task<CommandResponse<(error)>>", "PutCommandAsync(" + url + ")", null);
                }

                return (string.Empty, string.Empty, "PUT command with a result requires a body payload");
            case "DELETE":
                if (bodyParam is not null)
                {
                    return (string.Empty, string.Empty, "DELETE command with a body has no matching base helper");
                }

                if (hasResult)
                {
                    return ("Task<CommandResponse<" + view + ", (error)>>",
                        "DeleteCommandAsync<" + view + ">(" + url + ")", null);
                }

                return ("Task<CommandResponse<(error)>>", "DeleteCommandAsync(" + url + ")", null);
            default:
                return (string.Empty, string.Empty, "unsupported HTTP verb '" + verb + "' for a command");
        }
    }

    private (string UrlExpression, List<RouteParam> RouteParams, string? Diagnostic) BuildUrlExpression(
        ManifestEndpoint endpoint,
        HashSet<string> nullableRouteParams)
    {
        var route = endpoint.Route;
        var routeParams = new List<RouteParam>();
        var needsInterpolation = false;
        var sb = new StringBuilder();
        var last = 0;

        foreach (Match match in RouteTokenRegex.Matches(route))
        {
            sb.Append(route, last, match.Index - last);
            last = match.Index + match.Length;

            var tokenName = match.Groups[2].Value;
            var constraint = match.Groups[3].Value;
            var parameter = endpoint.Parameters.FirstOrDefault(p => p.Source == ParameterSource.Route
                                                                    && string.Equals(
                                                                        p.RouteToken ?? p.Name,
                                                                        tokenName,
                                                                        StringComparison.OrdinalIgnoreCase));
            if (parameter is null)
            {
                // Ambient API-version tokens (from /api/v{version:apiVersion} route groups) are substituted with
                // the configured version rather than treated as a missing parameter.
                if (IsVersionToken(tokenName, constraint))
                {
                    sb.Append(ApiVersion);
                    continue;
                }

                return (string.Empty, new List<RouteParam>(), $"route token '{tokenName}' has no matching parameter");
            }

            var isNullable = nullableRouteParams.Contains(tokenName) || parameter.IsNullable;
            routeParams.Add(new RouteParam(parameter, isNullable));
            var paramName = ToCamelCase(parameter.Name);

            if (isNullable)
            {
                sb.Append('{').Append('(').Append(paramName).Append("?.ToString() ?? \"-\")").Append('}');
            }
            else
            {
                sb.Append('{').Append(paramName).Append('}');
            }

            needsInterpolation = true;
        }

        sb.Append(route, last, route.Length - last);
        var routeLiteral = sb.ToString();
        var routeExpr = (needsInterpolation ? "$\"" : "\"") + routeLiteral + "\"";

        return (routeExpr, routeParams, null);
    }

    private static string AppendQuery(string urlExpr, List<MethodParam> parameters)
    {
        var queryParams = parameters.Where(p => p.WireKey is not null).ToList();
        if (queryParams.Count == 0)
        {
            return urlExpr;
        }

        // The query-string key is the wire name (camelCase of the original parameter); the value reference is the
        // resolved (uniquified) signature variable, so a route/query name collision can't bind the query to the
        // wrong variable.
        var builder = new StringBuilder("new QueryStringBuilder()");
        foreach (var query in queryParams)
        {
            builder.Append(".Add(\"").Append(query.WireKey).Append("\", ").Append(query.Name).Append(')');
        }

        builder.Append(".Build()");
        return urlExpr + " + " + builder;
    }

    private static string StripRequestSuffix(string requestTypeName)
    {
        var name = requestTypeName;
        var backtick = name.IndexOf('`');
        if (backtick >= 0)
        {
            name = name.Substring(0, backtick);
        }

        if (name.EndsWith("Query", StringComparison.Ordinal))
        {
            name = name.Substring(0, name.Length - "Query".Length);
        }
        else if (name.EndsWith("Command", StringComparison.Ordinal))
        {
            name = name.Substring(0, name.Length - "Command".Length);
        }

        return name;
    }

    private static string DeriveMethodName(string requestTypeName) => StripRequestSuffix(requestTypeName) + "Async";

    private static string DerivePocoName(string requestTypeName) => StripRequestSuffix(requestTypeName) + "Payload";

    /// <summary>The generated POCO name for a command body, or <c>null</c> when no POCO is generated for it.</summary>
    private string? ResolveBodyTypeOverride(ManifestEndpoint endpoint, ManifestParameter? bodyParam)
    {
        if (bodyParam is null || endpoint.PayloadContract is null)
        {
            return null;
        }

        return _pocoNameByBodyType.TryGetValue(BodyKey(bodyParam.ClrType), out var poco) ? poco : null;
    }

    /// <summary>A stable identity key for a body type, so the same command mapped at several routes shares one POCO.</summary>
    private static string BodyKey(ClrTypeRef type)
    {
        var ns = type.Namespace.Length > 0 ? type.Namespace + "." : string.Empty;
        var args = type.GenericArguments.Length > 0
            ? "<" + string.Join(",", type.GenericArguments.Select(BodyKey)) + ">"
            : string.Empty;
        var array = type.IsArray
            ? "[" + (type.ArrayRank > 1 ? new string(',', type.ArrayRank - 1) : string.Empty) + "]"
            : string.Empty;
        return ns + type.Name + args + array + (type.IsNullable ? "?" : string.Empty);
    }

    private static bool IsVersionToken(string tokenName, string constraint)
    {
        return string.Equals(tokenName, "version", StringComparison.OrdinalIgnoreCase)
               || constraint.Contains("apiVersion", StringComparison.OrdinalIgnoreCase);
    }

    private static string StripTrailingNullable(string type)
    {
        return type.EndsWith("?", StringComparison.Ordinal) ? type[..^1] : type;
    }

    private static ClrTypeRef GetElement(ClrTypeRef? responseType)
    {
        if (responseType is not null && responseType.GenericArguments.Length > 0)
        {
            return responseType.GenericArguments[0];
        }

        return new ClrTypeRef { Namespace = "System", Name = "Object" };
    }

    private static string ToCamelCase(string name)
    {
        if (name.Length == 0)
        {
            return name;
        }

        if (name.Length == 1)
        {
            return name.ToLowerInvariant();
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string UniqueName(string preferred, HashSet<string> used)
    {
        var candidate = preferred;
        var index = 1;
        while (used.Contains(candidate))
        {
            candidate = preferred + index++;
        }

        used.Add(candidate);
        return candidate;
    }

    private static HashSet<string> BuildUsings(IEnumerable<string> imported)
    {
        var usings = new HashSet<string>(imported)
        {
            "System.Collections.Generic",
            "System.Threading.Tasks",
            "Cnblogs.Architecture.Ddd.Cqrs.Abstractions",
            "Cnblogs.Architecture.Ddd.Cqrs.ServiceAgent",
            "Cnblogs.Architecture.Ddd.Infrastructure.Abstractions"
        };
        return usings;
    }

    private string RenderInterface(
        ManifestGroup group,
        string @namespace,
        List<MethodPlan> plans,
        HashSet<string> usings)
    {
        var renderer = new ClrTypeRenderer();
        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        foreach (var u in usings.OrderBy(u => u, StringComparer.Ordinal))
        {
            sb.Append("using ").Append(u).Append(";\n");
        }

        sb.Append("\nnamespace ").Append(@namespace).Append(";\n\n");
        sb.Append("public partial interface I").Append(group.Name).Append("Service\n{\n");
        foreach (var plan in plans.Where(p => !p.IsSkipped))
        {
            sb.Append("    ").Append(InjectErrorType(plan.ReturnType, group, renderer)).Append(' ').Append(plan.Name)
                .Append('(').Append(RenderParams(plan)).Append(");\n");
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private string RenderClass(ManifestGroup group, string @namespace, List<MethodPlan> plans, HashSet<string> usings)
    {
        var errorBase = group.ErrorType is null
            ? "CqrsServiceAgent"
            : "CqrsServiceAgent<" + RenderErrorType(group) + ">";
        var renderer = new ClrTypeRenderer();

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        foreach (var u in usings.OrderBy(u => u, StringComparer.Ordinal))
        {
            sb.Append("using ").Append(u).Append(";\n");
        }

        sb.Append("\nnamespace ").Append(@namespace).Append(";\n\n");
        sb.Append("public partial class ").Append(group.Name).Append("Service(HttpClient httpClient) : ")
            .Append(errorBase).Append("(httpClient), I").Append(group.Name).Append("Service\n{\n");

        foreach (var plan in plans)
        {
            if (plan.IsSkipped)
            {
                sb.Append("    // not generated: ").Append(plan.Name).Append(": ").Append(plan.SkipReason).Append('\n');
                continue;
            }

            // The command return type references the group error type; rewrite the placeholder here.
            var returnType = InjectErrorType(plan.ReturnType, group, renderer);
            sb.Append("    public ").Append(returnType).Append(' ').Append(plan.Name).Append('(')
                .Append(RenderParams(plan))
                .Append(")\n        => ").Append(plan.BodyExpression).Append(";\n\n");
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static string RenderParams(MethodPlan plan)
    {
        return string.Join(", ", plan.Parameters.Select(p => p.Type + " " + p.Name + (p.Default ?? string.Empty)));
    }

    private string RenderErrorType(ManifestGroup group)
    {
        var renderer = new ClrTypeRenderer();
        return renderer.Render(group.ErrorType);
    }

    private static string InjectErrorType(string returnType, ManifestGroup group, ClrTypeRenderer renderer)
    {
        if (!returnType.Contains("(error)", StringComparison.Ordinal))
        {
            return returnType;
        }

        var error = group.ErrorType is null ? "ServiceAgentError" : renderer.Render(group.ErrorType);
        return returnType.Replace("(error)", error);
    }

    private string RenderExtensions(EndpointManifest manifest, string @namespace)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        sb.Append("using Cnblogs.Architecture.Ddd.Cqrs.ServiceAgent;\n");
        sb.Append("using Microsoft.Extensions.DependencyInjection;\n\n");
        sb.Append("namespace ").Append(@namespace).Append(";\n\n");
        sb.Append("public static partial class ServiceAgentExtensions\n{\n");
        sb.Append(
            "    public static IServiceCollection AddServiceAgents(this IServiceCollection services, string baseUri)\n    {\n");
        foreach (var group in manifest.Groups)
        {
            sb.Append("        services.AddServiceAgent<I").Append(group.Name).Append("Service, ").Append(group.Name)
                .Append("Service>(baseUri);\n");
        }

        sb.Append("        return services;\n    }\n}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Emit one POCO per payload contract: a mutable class mirroring the command's settable properties, so the
    ///     generated client references this generated type instead of the command type's assembly.
    /// </summary>
    private List<EmittedFile> RenderPayloadContracts(string @namespace)
    {
        var files = new List<EmittedFile>();
        foreach (var poco in _pocoDefinitions.Values.OrderBy(p => p.Name, StringComparer.Ordinal))
        {
            // Render the property body first — renderer.Render records the namespaces the property types depend on,
            // which we then emit as using directives above the class.
            var renderer = new ClrTypeRenderer();
            var body = new StringBuilder();
            foreach (var property in poco.Properties)
            {
                var type = renderer.Render(property.ClrType);
                if (property is { IsNullable: true, ClrType.IsNullable: false })
                {
                    type += "?";
                }

                body.Append("    public ").Append(type).Append(' ').Append(property.Name).Append(" { get; set; }\n");
            }

            var sb = new StringBuilder();
            sb.Append(AutoGeneratedBanner);
            foreach (var u in renderer.ImportedNamespaces.OrderBy(u => u, StringComparer.Ordinal))
            {
                sb.Append("using ").Append(u).Append(";\n");
            }

            sb.Append("\nnamespace ").Append(@namespace).Append(";\n\n");
            sb.Append("public class ").Append(poco.Name).Append("\n{\n").Append(body).Append("}\n");
            files.Add(new EmittedFile { FileName = poco.Name + ".cs", Content = sb.ToString() });
        }

        return files;
    }

    private sealed record RouteParam(ManifestParameter Parameter, bool IsNullable);

    private sealed record PocoDefinition(string Name, List<PayloadProperty> Properties);

    private sealed record MethodParam(string Name, string Type, string? Default, string? WireKey = null);

    private sealed record MethodPlan
    {
        public required string Name { get; init; }
        public string ReturnType { get; set; } = string.Empty;
        public List<MethodParam> Parameters { get; set; } = [];
        public string BodyExpression { get; set; } = string.Empty;
        public bool IsSkipped { get; set; }
        public string? SkipReason { get; set; }

        public static MethodPlan Skipped(string name, string reason)
        {
            return new MethodPlan
            {
                Name = name,
                IsSkipped = true,
                SkipReason = reason
            };
        }
    }
}
