using System.Text;
using System.Text.RegularExpressions;
using Cnblogs.Architecture.Tool.Manifest;

namespace Cnblogs.Architecture.Tool.Generation;

/// <summary>
///     Turns an <see cref="EndpointManifest" /> into generated C# source files: one <c>IXxxService</c> /
///     <c>XxxService</c> pair per group, plus a <c>ServiceAgentExtensions</c> DI-registration file. Collapses
///     nullable-route expansions into single methods and maps each endpoint shape to the matching
///     <c>CqrsServiceAgent&lt;TError&gt;</c> helper.
/// </summary>
internal sealed class ServiceAgentEmitter
{
    private const string AutoGeneratedBanner =
        "// <auto-generated>\n" +
        "//     This code was generated by cnb-arch-tool (dotnet cnb serviceagent generate).\n" +
        "//     Do not edit manually; regenerate by running the tool against the API project.\n" +
        "// </auto-generated>\n" +
        "#nullable enable\n";

    private static readonly Regex RouteTokenRegex = new(@"\{(\*?)([A-Za-z_][A-Za-z0-9_]*)([^}]*)\}", RegexOptions.Compiled);

    private readonly List<string> _diagnostics = [];

    /// <summary>Warnings collected during emission (e.g. skipped endpoint shapes).</summary>
    public IReadOnlyList<string> Diagnostics => _diagnostics;

    /// <summary>
    ///     The API version substituted for <c>{version:apiVersion}</c> route tokens (the API-versioning route-group
    ///     convention). Defaults to <c>"1"</c>.
    /// </summary>
    public string ApiVersion { get; init; } = "1";

    /// <summary>Emit all source files for the manifest, using <paramref name="namespace" /> for the generated types.</summary>
    public List<EmittedFile> Emit(EndpointManifest manifest, string @namespace)
    {
        _diagnostics.Clear();
        var files = new List<EmittedFile>();
        foreach (var group in manifest.Groups)
        {
            var renderer = new ClrTypeRenderer();
            var plans = BuildPlans(group, renderer);
            var usings = BuildUsings(renderer.ImportedNamespaces, plans);
            files.Add(new EmittedFile { FileName = "I" + group.Name + "Service.cs", Content = RenderInterface(group, @namespace, plans, usings) });
            files.Add(new EmittedFile { FileName = group.Name + "Service.cs", Content = RenderClass(group, @namespace, plans, usings) });
        }

        files.Add(new EmittedFile { FileName = "ServiceAgentExtensions.cs", IsExtensionsFile = true, Content = RenderExtensions(manifest, @namespace) });
        return files;
    }

    private List<MethodPlan> BuildPlans(ManifestGroup group, ClrTypeRenderer renderer)
    {
        // Render the error type so its namespace is collected into the file's using set.
        if (group.ErrorType is not null)
        {
            renderer.Render(group.ErrorType);
        }

        var clusters = ClusterEndpoints(group.Endpoints);
        var plans = new List<MethodPlan>();
        foreach (var cluster in clusters)
        {
            plans.AddRange(BuildPlansForCluster(cluster, renderer));
        }

        // C# requires required parameters before optional ones; stable-partition so this holds regardless of how
        // route/query/body params were ordered (e.g. nullable route params carry '= null' defaults).
        foreach (var plan in plans)
        {
            plan.Parameters = OrderByOptionality(plan.Parameters);
        }

        SkipDuplicateSignatures(plans);
        return plans;
    }

    private static List<MethodParam> OrderByOptionality(List<MethodParam> parameters)
    {
        return parameters.Where(p => p.Default is null)
            .Concat(parameters.Where(p => p.Default is not null))
            .ToList();
    }

    private void SkipDuplicateSignatures(List<MethodPlan> plans)
    {
        // Two endpoints (e.g. the same command mapped at different routes) can yield methods with identical name
        // and parameter types. C# forbids duplicate declarations, so keep the first and skip the rest.
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var plan in plans)
        {
            if (plan.IsSkipped)
            {
                continue;
            }

            var signature = plan.Name + "(" + string.Join(",", plan.Parameters.Select(p => p.Type)) + ")";
            if (!seen.Add(signature))
            {
                plan.IsSkipped = true;
                plan.SkipReason = "duplicate method signature (same name and parameter types as another endpoint); "
                    + "split the route groups with WithServiceAgentGroup or use a distinct route";
                _diagnostics.Add($"Skipped duplicate '{plan.Name}' (same signature as another endpoint).");
            }
        }
    }

    /// <summary>
    ///     Group endpoints that resolve to the same generated method: nullable-route expansions of one
    ///     <c>MapQuery</c> call share a request type and a normalized route shape and collapse into one method.
    /// </summary>
    private List<List<ManifestEndpoint>> ClusterEndpoints(List<ManifestEndpoint> endpoints)
    {
        return endpoints
            .GroupBy(e => (e.RequestTypeName, NormalizeRoute(e.Route), e.HttpMethod, NonRouteSignature(e)))
            .Select(g => g.ToList())
            .ToList();
    }

    private static string NonRouteSignature(ManifestEndpoint endpoint)
    {
        var nonRoute = endpoint.Parameters.Where(p => p.Source != ParameterSource.Route).Select(p => p.Name + p.Source);
        return string.Join("|", nonRoute);
    }

    private static string NormalizeRoute(string route)
    {
        var tokenized = RouteTokenRegex.Replace(route, "{}");
        var segments = tokenized.Split('/');
        for (var i = 0; i < segments.Length; i++)
        {
            if (segments[i] == "-")
            {
                segments[i] = "{}";
            }
        }

        return string.Join('/', segments);
    }

    private List<MethodPlan> BuildPlansForCluster(List<ManifestEndpoint> cluster, ClrTypeRenderer renderer)
    {
        var canonical = cluster.OrderByDescending(e => e.Route.Count(c => c == '{')).First();
        var name = DeriveMethodName(canonical.RequestTypeName);
        var nullableRouteParams = canonical.NullableRouteParameters.ToHashSet(StringComparer.OrdinalIgnoreCase);

        var plans = new List<MethodPlan>();

        // Primary method (GET item/list/paged, or a command).
        var primary = BuildPrimaryPlan(canonical, name, nullableRouteParams, renderer);
        if (primary is not null)
        {
            plans.Add(primary);
        }

        // HEAD companion for single-item queries that enabled it. Guard on the skip flag (BuildPrimaryPlan returns
        // a Skipped plan, never null) and on the Item shape (HEAD/404 semantics only hold for single-item lookups;
        // list/paged queries never return 404).
        if (canonical.IsQuery
            && canonical.EnableHead
            && primary is { IsSkipped: false }
            && canonical.ResponseShape == ResponseShape.Item)
        {
            plans.Add(BuildHeadPlan(canonical, name, nullableRouteParams, renderer));
        }

        return plans;
    }

    private MethodPlan BuildPrimaryPlan(
        ManifestEndpoint endpoint,
        string name,
        HashSet<string> nullableRouteParams,
        ClrTypeRenderer renderer)
    {
        var paramNames = new HashSet<string>(StringComparer.Ordinal);

        var (urlExpr, routeParams, urlDiagnostic) = BuildUrlExpression(endpoint, nullableRouteParams, renderer, paramNames);
        if (urlDiagnostic is not null)
        {
            _diagnostics.Add($"Skipped '{name}' ({endpoint.HttpMethod} {endpoint.Route}): {urlDiagnostic}.");
            return MethodPlan.Skipped(name, urlDiagnostic);
        }

        var queryParams = endpoint.Parameters.Where(p => p.Source == ParameterSource.Query).ToList();
        var bodyParam = endpoint.Parameters.FirstOrDefault(p => p.Source == ParameterSource.Body);

        List<MethodParam> signature;
        string returnType;
        string call;

        if (endpoint.IsQuery)
        {
            var paged = endpoint.ResponseShape == ResponseShape.PagedList;
            var filterQueryParams = paged
                ? queryParams.Where(p => !IsPagingProperty(p.Name)).ToList()
                : queryParams;

            signature = BuildQuerySignature(routeParams, filterQueryParams, paged, nullableRouteParams, renderer, paramNames);
            var fullUrl = AppendQuery(urlExpr, signature);

            if (endpoint.ResponseShape == ResponseShape.Item)
            {
                // The renderer already appends '?' for Nullable<T>; strip it so we add exactly one (Task<T?>).
                var view = StripTrailingNullable(renderer.Render(endpoint.ResponseType));
                returnType = "Task<" + view + "?>";
                call = "GetItemAsync<" + view + ">(" + fullUrl + ")";
            }
            else if (endpoint.ResponseShape == ResponseShape.List)
            {
                var element = renderer.Render(GetElement(endpoint.ResponseType));
                returnType = "Task<List<" + element + ">>";
                call = "ListItemsAsync<List<" + element + ">>(" + fullUrl + ")";
            }
            else if (endpoint.ResponseShape == ResponseShape.PagedList)
            {
                var element = renderer.Render(GetElement(endpoint.ResponseType));
                returnType = "Task<PagedList<" + element + ">>";
                call = "ListPagedItemsAsync<" + element + ">(" + fullUrl + ", pageIndex, pageSize, orderByString)";
            }
            else
            {
                _diagnostics.Add($"Skipped '{name}' ({endpoint.HttpMethod} {endpoint.Route}): unsupported query response shape {endpoint.ResponseShape}.");
                return MethodPlan.Skipped(name, "unsupported query response shape");
            }
        }
        else
        {
            signature = BuildCommandSignature(routeParams, queryParams, bodyParam, renderer, paramNames);
            var fullUrl = AppendQuery(urlExpr, signature);
            var (cmdReturn, cmdCall, cmdReason) = BuildCommandCall(endpoint, fullUrl, bodyParam, renderer);
            if (cmdReason is not null)
            {
                _diagnostics.Add($"Skipped '{name}' ({endpoint.HttpMethod} {endpoint.Route}): {cmdReason}.");
                return MethodPlan.Skipped(name, cmdReason);
            }

            returnType = cmdReturn;
            call = cmdCall;
        }

        return new MethodPlan
        {
            Name = name,
            ReturnType = returnType,
            Parameters = signature,
            BodyExpression = call,
            IsSkipped = false
        };
    }

    private MethodPlan BuildHeadPlan(
        ManifestEndpoint endpoint,
        string name,
        HashSet<string> nullableRouteParams,
        ClrTypeRenderer renderer)
    {
        var paramNames = new HashSet<string>(StringComparer.Ordinal);
        var (urlExpr, routeParams, _) = BuildUrlExpression(endpoint, nullableRouteParams, renderer, paramNames);
        var queryParams = endpoint.Parameters.Where(p => p.Source == ParameterSource.Query && !IsPagingProperty(p.Name)).ToList();
        var signature = BuildQuerySignature(routeParams, queryParams, false, nullableRouteParams, renderer, paramNames);
        var fullUrl = AppendQuery(urlExpr, signature);
        var baseName = name.EndsWith("Async", StringComparison.Ordinal)
            ? name.Substring(0, name.Length - "Async".Length)
            : name;
        if (baseName.StartsWith("Get", StringComparison.Ordinal))
        {
            baseName = baseName.Substring("Get".Length);
        }

        var headName = "Has" + baseName + "Async";

        return new MethodPlan
        {
            Name = headName,
            ReturnType = "Task<bool>",
            Parameters = signature,
            BodyExpression = "HasItemAsync(" + fullUrl + ")",
            IsSkipped = false
        };
    }

    private static bool IsPagingProperty(string name)
    {
        return string.Equals(name, "PagingParams", StringComparison.OrdinalIgnoreCase)
            || string.Equals(name, "OrderByString", StringComparison.OrdinalIgnoreCase);
    }

    private List<MethodParam> BuildCommandSignature(
        List<RouteParam> routeParams,
        List<ManifestParameter> queryParams,
        ManifestParameter? bodyParam,
        ClrTypeRenderer renderer,
        HashSet<string> usedNames)
    {
        var signature = new List<MethodParam>();
        // The body argument is always named 'payload' (the base helper call uses that literal); reserve it first so
        // a query/route parameter whose camelCase name is 'payload' is uniqued (e.g. payload1) instead of colliding.
        if (bodyParam is not null)
        {
            usedNames.Add("payload");
        }

        AddRouteParams(signature, routeParams, renderer, usedNames);
        foreach (var query in queryParams)
        {
            signature.Add(BuildParam(query, renderer, usedNames, forceCamel: true));
        }

        if (bodyParam is not null)
        {
            signature.Add(BuildBodyParam(bodyParam, renderer, usedNames));
        }

        return signature;
    }

    private List<MethodParam> BuildQuerySignature(
        List<RouteParam> routeParams,
        List<ManifestParameter> queryParams,
        bool paged,
        HashSet<string> nullableRouteParams,
        ClrTypeRenderer renderer,
        HashSet<string> usedNames)
    {
        var signature = new List<MethodParam>();
        AddRouteParams(signature, routeParams, renderer, usedNames);
        foreach (var query in queryParams)
        {
            signature.Add(BuildParam(query, renderer, usedNames, forceCamel: true));
        }

        if (paged)
        {
            signature.Add(new MethodParam("pageIndex", "int?", " = null"));
            signature.Add(new MethodParam("pageSize", "int?", " = null"));
            signature.Add(new MethodParam("orderByString", "string?", " = null"));
        }

        return signature;
    }

    private void AddRouteParams(List<MethodParam> signature, List<RouteParam> routeParams, ClrTypeRenderer renderer, HashSet<string> usedNames)
    {
        foreach (var route in routeParams)
        {
            var type = renderer.Render(route.Parameter.ClrType);
            if (route.IsNullable && !route.Parameter.ClrType.IsNullable)
            {
                type += "?";
            }

            var paramName = UniqueName(ToCamelCase(route.Parameter.Name), usedNames);
            signature.Add(new MethodParam(paramName, type, route.IsNullable ? " = null" : null));
        }
    }

    private MethodParam BuildParam(ManifestParameter parameter, ClrTypeRenderer renderer, HashSet<string> usedNames, bool forceCamel)
    {
        var type = renderer.Render(parameter.ClrType);
        if (parameter.IsNullable && !parameter.ClrType.IsNullable)
        {
            type += "?";
        }

        var name = UniqueName(forceCamel ? ToCamelCase(parameter.Name) : parameter.Name, usedNames);
        var @default = parameter.HasDefaultValue && parameter.DefaultValueLiteral is not null
            ? " = " + parameter.DefaultValueLiteral
            : (parameter.IsNullable ? " = null" : null);
        return new MethodParam(name, type, @default, ToCamelCase(parameter.Name));
    }

    private static MethodParam BuildBodyParam(ManifestParameter parameter, ClrTypeRenderer renderer, HashSet<string> usedNames)
    {
        var type = renderer.Render(parameter.ClrType);
        if (parameter is { IsNullable: true, ClrType.IsNullable: false })
        {
            type += "?";
        }

        return new MethodParam("payload", type, null);
    }

    /// <summary>
    ///     Build the return type (with an <c>(error)</c> placeholder for the group's error type, replaced later) and
    ///     the base-class call expression for a command. Returns a skip reason when no base helper matches the shape.
    /// </summary>
    private (string ReturnType, string Call, string? Reason) BuildCommandCall(
        ManifestEndpoint endpoint,
        string url,
        ManifestParameter? bodyParam,
        ClrTypeRenderer renderer)
    {
        var verb = endpoint.HttpMethod.ToUpperInvariant();
        var hasResult = endpoint.ResponseShape == ResponseShape.Item && endpoint.ResponseType is not null;
        var view = hasResult ? renderer.Render(endpoint.ResponseType) : null;
        var payloadType = bodyParam is null ? null : renderer.Render(bodyParam.ClrType);

        switch (verb)
        {
            case "POST":
                if (hasResult && bodyParam is not null)
                {
                    return ("Task<CommandResponse<" + view + ", (error)>>", "PostCommandAsync<" + view + ", " + payloadType + ">(" + url + ", payload)", null);
                }

                if (!hasResult && bodyParam is not null)
                {
                    return ("Task<CommandResponse<(error)>>", "PostCommandAsync<" + payloadType + ">(" + url + ", payload)", null);
                }

                if (!hasResult && bodyParam is null)
                {
                    return ("Task<CommandResponse<(error)>>", "PostCommandAsync(" + url + ")", null);
                }

                return (string.Empty, string.Empty, "POST command with a result requires a body payload");
            case "PUT":
                if (hasResult && bodyParam is not null)
                {
                    return ("Task<CommandResponse<" + view + ", (error)>>", "PutCommandAsync<" + view + ", " + payloadType + ">(" + url + ", payload)", null);
                }

                if (!hasResult && bodyParam is not null)
                {
                    return ("Task<CommandResponse<(error)>>", "PutCommandAsync<" + payloadType + ">(" + url + ", payload)", null);
                }

                if (!hasResult && bodyParam is null)
                {
                    return ("Task<CommandResponse<(error)>>", "PutCommandAsync(" + url + ")", null);
                }

                return (string.Empty, string.Empty, "PUT command with a result requires a body payload");
            case "DELETE":
                if (bodyParam is not null)
                {
                    return (string.Empty, string.Empty, "DELETE command with a body has no matching base helper");
                }

                if (hasResult)
                {
                    return ("Task<CommandResponse<" + view + ", (error)>>", "DeleteCommandAsync<" + view + ">(" + url + ")", null);
                }

                return ("Task<CommandResponse<(error)>>", "DeleteCommandAsync(" + url + ")", null);
            default:
                return (string.Empty, string.Empty, "unsupported HTTP verb '" + verb + "' for a command");
        }
    }

    private static bool IsValueType(ClrTypeRef type)
    {
        // Rendered value-type keywords (Nullable<T> already unwrapped by the renderer's input).
        return type.Namespace == "System" && ValueKeywords.Contains(type.Name);
    }

    private static readonly HashSet<string> ValueKeywords =
    [
        "SByte", "Byte", "Int16", "UInt16", "Int32", "UInt32", "Int64", "UInt64",
        "IntPtr", "UIntPtr", "Char", "Boolean", "Single", "Double", "Decimal",
        "DateTime", "DateTimeOffset", "TimeSpan", "DateOnly", "TimeOnly", "Guid"
    ];

    private (string UrlExpression, List<RouteParam> RouteParams, string? Diagnostic) BuildUrlExpression(
        ManifestEndpoint endpoint,
        HashSet<string> nullableRouteParams,
        ClrTypeRenderer renderer,
        HashSet<string> usedNames)
    {
        var route = endpoint.Route;
        var routeParams = new List<RouteParam>();
        var needsInterpolation = false;
        var sb = new StringBuilder();
        var last = 0;

        foreach (Match match in RouteTokenRegex.Matches(route))
        {
            sb.Append(route, last, match.Index - last);
            last = match.Index + match.Length;

            var tokenName = match.Groups[2].Value;
            var constraint = match.Groups[3].Value;
            var parameter = endpoint.Parameters.FirstOrDefault(
                p => p.Source == ParameterSource.Route
                    && string.Equals(p.RouteToken ?? p.Name, tokenName, StringComparison.OrdinalIgnoreCase));
            if (parameter is null)
            {
                // Ambient API-version tokens (from /api/v{version:apiVersion} route groups) are substituted with
                // the configured version rather than treated as a missing parameter.
                if (IsVersionToken(tokenName, constraint))
                {
                    sb.Append(ApiVersion);
                    continue;
                }

                return (string.Empty, new List<RouteParam>(), $"route token '{tokenName}' has no matching parameter");
            }

            var isNullable = nullableRouteParams.Contains(tokenName) || parameter.IsNullable;
            routeParams.Add(new RouteParam(parameter, isNullable));
            var paramName = ToCamelCase(parameter.Name);

            if (isNullable)
            {
                sb.Append('{').Append('(').Append(paramName).Append("?.ToString() ?? \"-\")").Append('}');
            }
            else
            {
                sb.Append('{').Append(paramName).Append('}');
            }

            needsInterpolation = true;
        }

        sb.Append(route, last, route.Length - last);
        var routeLiteral = sb.ToString();
        var routeExpr = (needsInterpolation ? "$\"" : "\"") + routeLiteral + "\"";

        return (routeExpr, routeParams, null);
    }

    private static string AppendQuery(string urlExpr, List<MethodParam> parameters)
    {
        var queryParams = parameters.Where(p => p.WireKey is not null).ToList();
        if (queryParams.Count == 0)
        {
            return urlExpr;
        }

        // The query-string key is the wire name (camelCase of the original parameter); the value reference is the
        // resolved (uniquified) signature variable, so a route/query name collision can't bind the query to the
        // wrong variable.
        var builder = new StringBuilder("new QueryStringBuilder()");
        foreach (var query in queryParams)
        {
            builder.Append(".Add(\"").Append(query.WireKey).Append("\", ").Append(query.Name).Append(')');
        }

        builder.Append(".Build()");
        return urlExpr + " + " + builder;
    }

    private static string DeriveMethodName(string requestTypeName)
    {
        var name = requestTypeName;
        var backtick = name.IndexOf('`');
        if (backtick >= 0)
        {
            name = name.Substring(0, backtick);
        }

        if (name.EndsWith("Query", StringComparison.Ordinal))
        {
            name = name.Substring(0, name.Length - "Query".Length);
        }
        else if (name.EndsWith("Command", StringComparison.Ordinal))
        {
            name = name.Substring(0, name.Length - "Command".Length);
        }

        return name + "Async";
    }

    private static bool IsVersionToken(string tokenName, string constraint)
    {
        return string.Equals(tokenName, "version", StringComparison.OrdinalIgnoreCase)
            || constraint.Contains("apiVersion", StringComparison.OrdinalIgnoreCase);
    }

    private static string StripTrailingNullable(string type)
    {
        return type.EndsWith("?", StringComparison.Ordinal) ? type[..^1] : type;
    }

    private static ClrTypeRef GetElement(ClrTypeRef? responseType)
    {
        if (responseType is not null && responseType.GenericArguments.Length > 0)
        {
            return responseType.GenericArguments[0];
        }

        return new ClrTypeRef { Namespace = "System", Name = "Object" };
    }

    private static string ToCamelCase(string name)
    {
        if (name.Length == 0)
        {
            return name;
        }

        if (name.Length == 1)
        {
            return name.ToLowerInvariant();
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string UniqueName(string preferred, HashSet<string> used)
    {
        var candidate = preferred;
        var index = 1;
        while (used.Contains(candidate))
        {
            candidate = preferred + index++;
        }

        used.Add(candidate);
        return candidate;
    }

    private static HashSet<string> BuildUsings(IEnumerable<string> imported, List<MethodPlan> plans)
    {
        var usings = new HashSet<string>(imported)
        {
            "System.Collections.Generic",
            "System.Threading.Tasks",
            "Cnblogs.Architecture.Ddd.Cqrs.Abstractions",
            "Cnblogs.Architecture.Ddd.Cqrs.ServiceAgent",
            "Cnblogs.Architecture.Ddd.Infrastructure.Abstractions"
        };
        return usings;
    }

    private string RenderInterface(ManifestGroup group, string @namespace, List<MethodPlan> plans, HashSet<string> usings)
    {
        var renderer = new ClrTypeRenderer();
        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        foreach (var u in usings.OrderBy(u => u, StringComparer.Ordinal))
        {
            sb.Append("using ").Append(u).Append(";\n");
        }

        sb.Append("\nnamespace ").Append(@namespace).Append(";\n\n");
        sb.Append("public partial interface I").Append(group.Name).Append("Service\n{\n");
        foreach (var plan in plans.Where(p => !p.IsSkipped))
        {
            sb.Append("    ").Append(InjectErrorType(plan.ReturnType, group, renderer)).Append(' ').Append(plan.Name)
                .Append('(').Append(RenderParams(plan)).Append(");\n");
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private string RenderClass(ManifestGroup group, string @namespace, List<MethodPlan> plans, HashSet<string> usings)
    {
        var errorBase = group.ErrorType is null ? "CqrsServiceAgent" : "CqrsServiceAgent<" + RenderErrorType(group) + ">";
        var renderer = new ClrTypeRenderer();

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        foreach (var u in usings.OrderBy(u => u, StringComparer.Ordinal))
        {
            sb.Append("using ").Append(u).Append(";\n");
        }

        sb.Append("\nnamespace ").Append(@namespace).Append(";\n\n");
        sb.Append("public partial class ").Append(group.Name).Append("Service(HttpClient httpClient) : ")
            .Append(errorBase).Append("(httpClient), I").Append(group.Name).Append("Service\n{\n");

        foreach (var plan in plans)
        {
            if (plan.IsSkipped)
            {
                sb.Append("    // not generated: ").Append(plan.Name).Append(": ").Append(plan.SkipReason).Append('\n');
                continue;
            }

            // The command return type references the group error type; rewrite the placeholder here.
            var returnType = InjectErrorType(plan.ReturnType, group, renderer);
            sb.Append("    public ").Append(returnType).Append(' ').Append(plan.Name).Append('(').Append(RenderParams(plan))
                .Append(")\n        => ").Append(plan.BodyExpression).Append(";\n\n");
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static string RenderParams(MethodPlan plan)
    {
        return string.Join(", ", plan.Parameters.Select(p => p.Type + " " + p.Name + (p.Default ?? string.Empty)));
    }

    private string RenderErrorType(ManifestGroup group)
    {
        var renderer = new ClrTypeRenderer();
        return renderer.Render(group.ErrorType);
    }

    private static string InjectErrorType(string returnType, ManifestGroup group, ClrTypeRenderer renderer)
    {
        if (!returnType.Contains("(error)", StringComparison.Ordinal))
        {
            return returnType;
        }

        var error = group.ErrorType is null ? "ServiceAgentError" : renderer.Render(group.ErrorType);
        return returnType.Replace("(error)", error);
    }

    private string RenderExtensions(EndpointManifest manifest, string @namespace)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGeneratedBanner);
        sb.Append("using Cnblogs.Architecture.Ddd.Cqrs.ServiceAgent;\n");
        sb.Append("using Microsoft.Extensions.DependencyInjection;\n\n");
        sb.Append("namespace ").Append(@namespace).Append(";\n\n");
        sb.Append("public static partial class ServiceAgentExtensions\n{\n");
        sb.Append("    public static IServiceCollection AddServiceAgents(this IServiceCollection services, string baseUri)\n    {\n");
        foreach (var group in manifest.Groups)
        {
            sb.Append("        services.AddServiceAgent<I").Append(group.Name).Append("Service, ").Append(group.Name)
                .Append("Service>(baseUri);\n");
        }

        sb.Append("        return services;\n    }\n}\n");
        return sb.ToString();
    }

    private sealed record RouteParam(ManifestParameter Parameter, bool IsNullable);

    private sealed record MethodParam(string Name, string Type, string? Default, string? WireKey = null);

    private sealed record MethodPlan
    {
        public required string Name { get; init; }
        public string ReturnType { get; set; } = string.Empty;
        public List<MethodParam> Parameters { get; set; } = [];
        public string BodyExpression { get; set; } = string.Empty;
        public bool IsSkipped { get; set; }
        public string? SkipReason { get; set; }

        public static MethodPlan Skipped(string name, string reason)
        {
            return new MethodPlan { Name = name, IsSkipped = true, SkipReason = reason };
        }
    }
}
