<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="AlibabaCloud.OSS.V2" Version="0.2.0" />
      <PackageReference Include="Aliyun.Credentials" Version="1.5.3" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cnblogs.Architecture.Ddd.Cqrs.DependencyInjection\Cnblogs.Architecture.Ddd.Cqrs.DependencyInjection.csproj" />
      <ProjectReference Include="..\Cnblogs.Architecture.Ddd.Infrastructure.Abstractions\Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.csproj" />
    </ItemGroup>

</Project>
