### YamlMime:ManagedReference
items:
- uid: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig`1
  commentId: T:Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig`1
  id: OrderBySegmentConfig`1
  parent: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  children:
  - Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig`1.RegisterSortableProperty``1(System.String,System.Linq.Expressions.Expression{System.Func{`0,``0}})
  langs:
  - csharp
  - vb
  name: OrderBySegmentConfig<TEntity>
  nameWithType: OrderBySegmentConfig<TEntity>
  fullName: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig<TEntity>
  type: Class
  source:
    remote:
      path: src/Cnblogs.Architecture.Ddd.Infrastructure.Abstractions/OrderBySegmentConfig.cs
      branch: add-docfx
      repo: https://github.com/cnblogs/Architecture.git
    id: OrderBySegmentConfig
    path: src/Cnblogs.Architecture.Ddd.Infrastructure.Abstractions/OrderBySegmentConfig.cs
    startLine: 82
  assemblies:
  - Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  namespace: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  summary: 管理可排序列的映射。
  example: []
  syntax:
    content: public static class OrderBySegmentConfig<TEntity>
    typeParameters:
    - id: TEntity
      description: The entity to config.
    content.vb: Public Module OrderBySegmentConfig(Of TEntity)
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  nameWithType.vb: OrderBySegmentConfig(Of TEntity)
  fullName.vb: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig(Of TEntity)
  name.vb: OrderBySegmentConfig(Of TEntity)
- uid: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig`1.RegisterSortableProperty``1(System.String,System.Linq.Expressions.Expression{System.Func{`0,``0}})
  commentId: M:Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig`1.RegisterSortableProperty``1(System.String,System.Linq.Expressions.Expression{System.Func{`0,``0}})
  id: RegisterSortableProperty``1(System.String,System.Linq.Expressions.Expression{System.Func{`0,``0}})
  parent: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig`1
  langs:
  - csharp
  - vb
  name: RegisterSortableProperty<TProperty>(string, Expression<Func<TEntity, TProperty>>)
  nameWithType: OrderBySegmentConfig<TEntity>.RegisterSortableProperty<TProperty>(string, Expression<Func<TEntity, TProperty>>)
  fullName: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig<TEntity>.RegisterSortableProperty<TProperty>(string, System.Linq.Expressions.Expression<System.Func<TEntity, TProperty>>)
  type: Method
  source:
    remote:
      path: src/Cnblogs.Architecture.Ddd.Infrastructure.Abstractions/OrderBySegmentConfig.cs
      branch: add-docfx
      repo: https://github.com/cnblogs/Architecture.git
    id: RegisterSortableProperty
    path: src/Cnblogs.Architecture.Ddd.Infrastructure.Abstractions/OrderBySegmentConfig.cs
    startLine: 90
  assemblies:
  - Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  namespace: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  summary: 注册新的可排序列。
  example: []
  syntax:
    content: public static void RegisterSortableProperty<TProperty>(string name, Expression<Func<TEntity, TProperty>> exp)
    parameters:
    - id: name
      type: System.String
      description: 列名。
    - id: exp
      type: System.Linq.Expressions.Expression{System.Func{{TEntity},{TProperty}}}
      description: 属性表达式。
    typeParameters:
    - id: TProperty
      description: 属性类型。
    content.vb: Public Shared Sub RegisterSortableProperty(Of TProperty)(name As String, exp As Expression(Of Func(Of TEntity, TProperty)))
  overload: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig`1.RegisterSortableProperty*
  nameWithType.vb: OrderBySegmentConfig(Of TEntity).RegisterSortableProperty(Of TProperty)(String, Expression(Of Func(Of TEntity, TProperty)))
  fullName.vb: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig(Of TEntity).RegisterSortableProperty(Of TProperty)(String, System.Linq.Expressions.Expression(Of System.Func(Of TEntity, TProperty)))
  name.vb: RegisterSortableProperty(Of TProperty)(String, Expression(Of Func(Of TEntity, TProperty)))
references:
- uid: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  commentId: N:Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  href: Cnblogs.html
  name: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  nameWithType: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  fullName: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
  spec.csharp:
  - uid: Cnblogs
    name: Cnblogs
    href: Cnblogs.html
  - name: .
  - uid: Cnblogs.Architecture
    name: Architecture
    href: Cnblogs.Architecture.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd
    name: Ddd
    href: Cnblogs.Architecture.Ddd.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd.Infrastructure
    name: Infrastructure
    href: Cnblogs.Architecture.Ddd.Infrastructure.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
    name: Abstractions
    href: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.html
  spec.vb:
  - uid: Cnblogs
    name: Cnblogs
    href: Cnblogs.html
  - name: .
  - uid: Cnblogs.Architecture
    name: Architecture
    href: Cnblogs.Architecture.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd
    name: Ddd
    href: Cnblogs.Architecture.Ddd.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd.Infrastructure
    name: Infrastructure
    href: Cnblogs.Architecture.Ddd.Infrastructure.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions
    name: Abstractions
    href: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig`1.RegisterSortableProperty*
  commentId: Overload:Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig`1.RegisterSortableProperty
  href: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig-1.html#Cnblogs_Architecture_Ddd_Infrastructure_Abstractions_OrderBySegmentConfig_1_RegisterSortableProperty__1_System_String_System_Linq_Expressions_Expression_System_Func__0___0___
  name: RegisterSortableProperty
  nameWithType: OrderBySegmentConfig<TEntity>.RegisterSortableProperty
  fullName: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig<TEntity>.RegisterSortableProperty
  nameWithType.vb: OrderBySegmentConfig(Of TEntity).RegisterSortableProperty
  fullName.vb: Cnblogs.Architecture.Ddd.Infrastructure.Abstractions.OrderBySegmentConfig(Of TEntity).RegisterSortableProperty
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Linq.Expressions.Expression{System.Func{{TEntity},{TProperty}}}
  commentId: T:System.Linq.Expressions.Expression{System.Func{``0,``1}}
  parent: System.Linq.Expressions
  definition: System.Linq.Expressions.Expression`1
  href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  name: Expression<Func<TEntity, TProperty>>
  nameWithType: Expression<Func<TEntity, TProperty>>
  fullName: System.Linq.Expressions.Expression<System.Func<TEntity, TProperty>>
  nameWithType.vb: Expression(Of Func(Of TEntity, TProperty))
  fullName.vb: System.Linq.Expressions.Expression(Of System.Func(Of TEntity, TProperty))
  name.vb: Expression(Of Func(Of TEntity, TProperty))
  spec.csharp:
  - uid: System.Linq.Expressions.Expression`1
    name: Expression
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  - name: <
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - name: TEntity
  - name: ','
  - name: " "
  - name: TProperty
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Linq.Expressions.Expression`1
    name: Expression
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: ','
  - name: " "
  - name: TProperty
  - name: )
  - name: )
- uid: System.Linq.Expressions.Expression`1
  commentId: T:System.Linq.Expressions.Expression`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  name: Expression<TDelegate>
  nameWithType: Expression<TDelegate>
  fullName: System.Linq.Expressions.Expression<TDelegate>
  nameWithType.vb: Expression(Of TDelegate)
  fullName.vb: System.Linq.Expressions.Expression(Of TDelegate)
  name.vb: Expression(Of TDelegate)
  spec.csharp:
  - uid: System.Linq.Expressions.Expression`1
    name: Expression
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  - name: <
  - name: TDelegate
  - name: '>'
  spec.vb:
  - uid: System.Linq.Expressions.Expression`1
    name: Expression
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  - name: (
  - name: Of
  - name: " "
  - name: TDelegate
  - name: )
- uid: System.Linq.Expressions
  commentId: N:System.Linq.Expressions
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Linq.Expressions
  nameWithType: System.Linq.Expressions
  fullName: System.Linq.Expressions
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Linq
    name: Linq
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq
  - name: .
  - uid: System.Linq.Expressions
    name: Expressions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Linq
    name: Linq
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq
  - name: .
  - uid: System.Linq.Expressions
    name: Expressions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions
