### YamlMime:ManagedReference
items:
- uid: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions
  commentId: T:Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions
  id: EntityConfigurationExtensions
  parent: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  children:
  - Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.IgnoreEntityDefaultProperties``1(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{``0})
  langs:
  - csharp
  - vb
  name: EntityConfigurationExtensions
  nameWithType: EntityConfigurationExtensions
  fullName: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions
  type: Class
  source:
    remote:
      path: src/Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework/EntityConfigurationExtensions.cs
      branch: add-docfx
      repo: https://github.com/cnblogs/Architecture.git
    id: EntityConfigurationExtensions
    path: src/Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework/EntityConfigurationExtensions.cs
    startLine: 9
  assemblies:
  - Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  namespace: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  summary: 实体配置使用的扩展方法。
  example: []
  syntax:
    content: public static class EntityConfigurationExtensions
    content.vb: Public Module EntityConfigurationExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.IgnoreEntityDefaultProperties``1(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{``0})
  commentId: M:Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.IgnoreEntityDefaultProperties``1(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{``0})
  id: IgnoreEntityDefaultProperties``1(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{``0})
  isExtensionMethod: true
  parent: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions
  langs:
  - csharp
  - vb
  name: IgnoreEntityDefaultProperties<TEntity>(EntityTypeBuilder<TEntity>)
  nameWithType: EntityConfigurationExtensions.IgnoreEntityDefaultProperties<TEntity>(EntityTypeBuilder<TEntity>)
  fullName: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.IgnoreEntityDefaultProperties<TEntity>(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>)
  type: Method
  source:
    remote:
      path: src/Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework/EntityConfigurationExtensions.cs
      branch: add-docfx
      repo: https://github.com/cnblogs/Architecture.git
    id: IgnoreEntityDefaultProperties
    path: src/Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework/EntityConfigurationExtensions.cs
    startLine: 19
  assemblies:
  - Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  namespace: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  summary: 不使用实体自带的 DateAdded, DateUpdated, Deleted 属性。
  example: []
  syntax:
    content: 'public static EntityTypeBuilder<TEntity> IgnoreEntityDefaultProperties<TEntity>(this EntityTypeBuilder<TEntity> builder) where TEntity : Entity'
    parameters:
    - id: builder
      type: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{{TEntity}}
      description: <xref href="Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder%601" data-throw-if-not-resolved="false"></xref>
    typeParameters:
    - id: TEntity
      description: 实体类型。
    return:
      type: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{{TEntity}}
      description: 配置好的 <xref href="Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder%601" data-throw-if-not-resolved="false"></xref>
    content.vb: Public Shared Function IgnoreEntityDefaultProperties(Of TEntity As Entity)(builder As EntityTypeBuilder(Of TEntity)) As EntityTypeBuilder(Of TEntity)
  overload: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.IgnoreEntityDefaultProperties*
  nameWithType.vb: EntityConfigurationExtensions.IgnoreEntityDefaultProperties(Of TEntity)(EntityTypeBuilder(Of TEntity))
  fullName.vb: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.IgnoreEntityDefaultProperties(Of TEntity)(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of TEntity))
  name.vb: IgnoreEntityDefaultProperties(Of TEntity)(EntityTypeBuilder(Of TEntity))
references:
- uid: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  commentId: N:Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  href: Cnblogs.html
  name: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  nameWithType: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  fullName: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
  spec.csharp:
  - uid: Cnblogs
    name: Cnblogs
    href: Cnblogs.html
  - name: .
  - uid: Cnblogs.Architecture
    name: Architecture
    href: Cnblogs.Architecture.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd
    name: Ddd
    href: Cnblogs.Architecture.Ddd.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd.Infrastructure
    name: Infrastructure
    href: Cnblogs.Architecture.Ddd.Infrastructure.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
    name: EntityFramework
    href: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.html
  spec.vb:
  - uid: Cnblogs
    name: Cnblogs
    href: Cnblogs.html
  - name: .
  - uid: Cnblogs.Architecture
    name: Architecture
    href: Cnblogs.Architecture.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd
    name: Ddd
    href: Cnblogs.Architecture.Ddd.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd.Infrastructure
    name: Infrastructure
    href: Cnblogs.Architecture.Ddd.Infrastructure.html
  - name: .
  - uid: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework
    name: EntityFramework
    href: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  commentId: T:Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  name: EntityTypeBuilder<TEntity>
  nameWithType: EntityTypeBuilder<TEntity>
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>
  nameWithType.vb: EntityTypeBuilder(Of TEntity)
  fullName.vb: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of TEntity)
  name.vb: EntityTypeBuilder(Of TEntity)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - name: TEntity
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
- uid: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.IgnoreEntityDefaultProperties*
  commentId: Overload:Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.IgnoreEntityDefaultProperties
  href: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.html#Cnblogs_Architecture_Ddd_Infrastructure_EntityFramework_EntityConfigurationExtensions_IgnoreEntityDefaultProperties__1_Microsoft_EntityFrameworkCore_Metadata_Builders_EntityTypeBuilder___0__
  name: IgnoreEntityDefaultProperties
  nameWithType: EntityConfigurationExtensions.IgnoreEntityDefaultProperties
  fullName: Cnblogs.Architecture.Ddd.Infrastructure.EntityFramework.EntityConfigurationExtensions.IgnoreEntityDefaultProperties
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{{TEntity}}
  commentId: T:Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{``0}
  parent: Microsoft.EntityFrameworkCore.Metadata.Builders
  definition: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  name: EntityTypeBuilder<TEntity>
  nameWithType: EntityTypeBuilder<TEntity>
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>
  nameWithType.vb: EntityTypeBuilder(Of TEntity)
  fullName.vb: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of TEntity)
  name.vb: EntityTypeBuilder(Of TEntity)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - name: TEntity
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders
  commentId: N:Microsoft.EntityFrameworkCore.Metadata.Builders
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.EntityFrameworkCore.Metadata.Builders
  nameWithType: Microsoft.EntityFrameworkCore.Metadata.Builders
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata
    name: Metadata
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders
    name: Builders
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata
    name: Metadata
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders
    name: Builders
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders
