name: Release Package

on:
  release:
    types:
      - published

jobs:
  pack:
    environment: nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-api-key: ${{ secrets.NUGETAPIKEY }}
      - name: Nuget Push
        run: |
          Version=${GITHUB_REF:10}
          dotnet build -c Release
          sed -i "s/\(<MongoAnalyzerRuleSetVersion>\)[^<]*\(<\/MongoAnalyzerRuleSetVersion>\)/\1$version\2/" src/Cnblogs.Architecture.Ddd.Cqrs.MongoDb.Analyzer/build/Cnblogs.Architecture.Ddd.Cqrs.MongoDb.Analyzer.props
          dotnet pack Cnblogs.Architecture.sln -p:Version="$Version" -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source -o "output"
          nuget push output/*.* -NonInteractive -Source https://api.nuget.org/v3/index.json
